### ISSUE TITLE
Can't Load Second DB

### ISSUE THREAD

**Issue by apayden** [anjlab/db-switch#2]
I have two identical tables on the same host, same login, everything, just different instances with different data.  When I try to run
```
ActiveRecord::Base.connect_to(:replica_one) do    
  @project = Project.first
end
```
With my `database.yml` looking like:
```
default: &default
  adapter: sqlserver
  host: HOST_NAME
  username: USERNAME
  password: PASSWORD
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db1

replica_one:
  development:
    <<: *default
    database: db2
```

The db switch does not occur.  I tried printing the `ActiveRecord::Base.configurations`, I get:
```
{
  "default": {
    "adapter": "sqlserver",
    "host": "HOST_NAME",
    "username": "USERNAME",
    "password": "PASSWORD",
    "pool": 5,
    "timeout": 5000
  },
  "development": {
    "adapter": "sqlserver",
    "host": "HOST_NAME",
    "username": "USERNAME",
    "password": "PASSWORD",
    "pool": 5,
    "timeout": 5000,
    "database": "crucible02"
  }
}
```
There is no mention of replica_one anywhere.  Is there a setup step that's missing in the README or something I'm doing wrong?
